ㅁㄹㄴㅇㄹㅁㅇㄴ

diff --git a/.github/workflows/test-frontend.yml b/.github/workflows/test-frontend.yml
--- a/.github/workflows/test-frontend.yml
+++ b/.github/workflows/test-frontend.yml
@@ -71,6 +71,13 @@ jobs:
         run: |
           ./mvnw clean install -DskipTests -am -pl zeppelin-integration -Pweb-classic -Pintegration -Pspark-scala-2.12 -Pspark-3.4 -Pweb-dist ${MAVEN_ARGS}
 
+      - name: Print Chrome and ChromeDriver version
+        run: |
+          echo "Chrome version:"
+          google-chrome --version || chromium-browser --version || echo "Chrome not found"
+          echo "ChromeDriver version:"
+          chromedriver --version || echo "ChromeDriver not found"
+
       - name: run tests
         run: |
           xvfb-run --auto-servernum --server-args="-screen 0 1600x1024x16" ./mvnw verify -DfailIfNoTests=false -pl zeppelin-integration -Pweb-classic -Pintegration -Pspark-scala-2.12 -Pspark-3.4 -Pweb-dist -Pusing-source-tree ${MAVEN_ARGS}
